apiVersion: database.postgres.example.com/v1alpha1
kind: PostgresCluster
metadata:
  labels:
    app.kubernetes.io/name: postgres-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgrescluster-sample
spec:
  # TODO: fill in spec fields
