resources:
- bases/database.postgres.example.com_postgresclusters.yaml
#+kubebuilder:scaffold:crdkustomizeresource

# [WEBHOOK]
patches:
- path: patches/webhook_in_postgresclusters.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER]
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

configurations:
- kustomizeconfig.yaml
